# Generated by Django 4.1.5 on 2023-02-02 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChampLexicale',
            fields=[
                ('id_ChampLexicale', models.IntegerField(primary_key=True, serialize=False)),
                ('NomChamp', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Langue',
            fields=[
                ('id_langue', models.IntegerField(primary_key=True, serialize=False)),
                ('libelleLangue', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MotFr',
            fields=[
                ('id_Mot', models.IntegerField(primary_key=True, serialize=False)),
                ('ecriture', models.TextField()),
                ('definition', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NiveauFormation',
            fields=[
                ('id_Niveau', models.IntegerField(primary_key=True, serialize=False)),
                ('libelleNiveauFormation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TempsVerbaux',
            fields=[
                ('id_TempsVerbaux', models.IntegerField(primary_key=True, serialize=False)),
                ('libelleTempsVerbaux', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id_theme', models.IntegerField(primary_key=True, serialize=False)),
                ('libelleThem', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VerbeFr',
            fields=[
                ('id_Verbe', models.IntegerField(primary_key=True, serialize=False)),
                ('libelleVerbe', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Regles',
            fields=[
                ('id_Regles', models.IntegerField(primary_key=True, serialize=False)),
                ('libelleConjuguer', models.TextField()),
                ('id_Langue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.langue')),
                ('id_TempsVerbaux', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.tempsverbaux')),
            ],
        ),
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('id_Dialogue', models.IntegerField(primary_key=True, serialize=False)),
                ('libelleDialogue', models.TextField(null=True)),
                ('audio', models.FileField(null=True, upload_to='public')),
                ('regles', models.TextField(null=True)),
                ('id_Langue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.langue')),
                ('id_Niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.niveauformation')),
                ('id_Themes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.theme')),
            ],
        ),
        migrations.CreateModel(
            name='Contenir',
            fields=[
                ('id_Contenir', models.IntegerField(primary_key=True, serialize=False)),
                ('continueChamp', models.TextField()),
                ('id_ChampLexicale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.champlexicale')),
                ('id_Mot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.motfr')),
                ('id_Niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.niveauformation')),
            ],
        ),
        migrations.CreateModel(
            name='Conjuguer',
            fields=[
                ('id_Conjuguer', models.IntegerField(primary_key=True, serialize=False)),
                ('libelleConjuguer', models.TextField()),
                ('id_Langue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.langue')),
                ('id_TempsVerbaux', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.tempsverbaux')),
                ('id_Verbe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.verbefr')),
            ],
        ),
    ]
