# Generated by Django 4.1.5 on 2023-02-02 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0002_alter_champlexicale_id_champlexicale_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regles',
            old_name='libelleConjuguer',
            new_name='libelleRegles',
        ),
    ]
