# Generated by Django 4.1.5 on 2023-02-03 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0003_rename_libelleconjuguer_regles_libelleregles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialogue',
            name='audio',
            field=models.FileField(null=True, upload_to='public/Dialogue'),
        ),
        migrations.CreateModel(
            name='Traduires',
            fields=[
                ('id_Traduire', models.AutoField(primary_key=True, serialize=False)),
                ('audio', models.FileField(null=True, upload_to='public/motTraduit')),
                ('id_Langue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.langue')),
                ('id_Mot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.motfr')),
            ],
        ),
    ]
