# Generated by Django 4.1.5 on 2023-02-04 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0006_rename_id_champlexicale_contenir_id_champlexicales'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contenir',
            old_name='id_Mot',
            new_name='id_Mots',
        ),
    ]
