# Generated by Django 4.1.5 on 2023-02-07 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0008_rename_id_champlexicales_contenir_id_champlexicale_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contenir',
            old_name='id_Mot',
            new_name='Motfr',
        ),
        migrations.RenameField(
            model_name='contenir',
            old_name='id_ChampLexicale',
            new_name='NomChamp',
        ),
    ]
