# Generated by Django 4.1.5 on 2023-02-07 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0009_rename_id_mot_contenir_motfr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenir',
            name='id_Niveau',
        ),
        migrations.AddField(
            model_name='champlexicale',
            name='id_Niveau',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='formation.niveauformation'),
        ),
    ]
