# Generated by Django 4.1.5 on 2023-02-07 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0011_remove_champlexicale_id_niveau_champlexicale_niveau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champlexicale',
            name='Niveau',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='niveau_Formation', to='formation.niveauformation'),
        ),
    ]
