# Generated by Django 4.1.5 on 2023-02-07 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0012_alter_champlexicale_niveau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenir',
            name='NomChamp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nom_Champ', to='formation.champlexicale'),
        ),
    ]
