# Generated by Django 4.1.5 on 2023-02-07 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0015_alter_champlexicale_niveau_alter_contenir_nomchamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='champlexicale',
            old_name='Niveau',
            new_name='Nivform',
        ),
    ]
