# Generated by Django 4.1.5 on 2023-02-08 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0016_rename_niveau_champlexicale_nivform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenir',
            name='Motfr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mots', to='formation.motfr'),
        ),
        migrations.AlterField(
            model_name='contenir',
            name='NomChamp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='champ', to='formation.champlexicale'),
        ),
    ]
