# Generated by Django 4.1.5 on 2023-02-08 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0017_alter_contenir_motfr_alter_contenir_nomchamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champlexicale',
            name='Nivform',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='niveau', to='formation.niveauformation'),
        ),
    ]
