# Generated by Django 4.1.5 on 2023-02-08 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0019_alter_traduires_id_mot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contenir',
            old_name='Motfr',
            new_name='id_Mot',
        ),
    ]
