# Generated by Django 4.1.5 on 2023-02-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0022_remove_motfr_id_contenir_contenir_id_mot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenir',
            name='continueChamp',
            field=models.TextField(null=True),
        ),
    ]
