# Generated by Django 4.1.5 on 2023-02-16 10:50

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0023_alter_contenir_continuechamp'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='champlexicale',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
