# Generated by Django 4.1.5 on 2023-02-16 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0024_alter_champlexicale_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='champlexicale',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='contenir',
            name='continueChamp',
        ),
    ]
