# Generated by Django 4.1.5 on 2023-02-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0025_alter_champlexicale_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='champlexicale',
            name='mot',
            field=models.ManyToManyField(to='formation.motfr'),
        ),
    ]
